name: Publish

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: use Node.js 14
              uses: actions/setup-node@v3

            - name: install
              run: npm install --ignore-scripts

            - name: build
              run: npm run dll:build

            - name: publish
              run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
