name: Publish

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://npm.pkg.github.com/

            - name: Configure CI Git User
              run: git config --global user.name '@ftrprf' && git config --global user.email 'developer@ftrprf.be' && git config pull.rebase false

            - name: cache node modules
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: install
              run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: build
              run: npm run dll:build

            - name: version
              run: npm version minor

            - name: push version
              run: git push --follow-tags

            - name: publish
              run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}